document.addEventListener('DOMContentLoaded',()=>{
const strategyStyle=document.createElement('link');strategyStyle.rel='stylesheet';strategyStyle.href='strategy.css';document.head.append(strategyStyle);
const g=JSON.parse(localStorage.getItem('atlas-goals')||'{"revenue":250000,"hours":30,"type":"High-value, strategic work","risk":"balanced"}');
function rs(){goalRevenue.value=g.revenue;goalHours.value=g.hours;goalType.value=g.type;goalRisk.value=g.risk;let a=data.filter(o=>o.status!=='watching').sort((x,y)=>score(y)-score(x));simulator.innerHTML=a.map(o=>'<label class="sim-item"><input type="checkbox" data-sim="'+o.id+'" checked><span>'+esc(o.title)+'</span><small>'+money(o.value)+' | '+Math.round(o.confidence*.55)+'% win likelihood</small></label>').join('');document.querySelectorAll('[data-sim]').forEach(x=>x.onchange=sim);memo();sources();sim()}
function sim(){let a=[...document.querySelectorAll('[data-sim]:checked')].map(x=>data.find(o=>o.id==x.dataset.sim)),value=a.reduce((n,o)=>n+o.value*o.confidence/100*o.fit/100,0),hours=a.reduce((n,o)=>n+Math.round(o.effort*.18),0),target=Number(goalRevenue.value)||g.revenue;simulationResult.innerHTML='<strong>'+money(value)+'</strong><span>risk-adjusted expected value</span><p>'+hours+' estimated delivery hours/week vs. '+(goalHours.value||g.hours)+' available. '+Math.round(value/target*100)+'% of quarterly target covered.</p>'}
function memo(){let a=[...data].sort((x,y)=>score(y)-score(x)),t=a[0],u=a.filter(o=>days(o)<=14&&o.status==='needs-review').length;strategyMemo.innerHTML='<div><p class="eyebrow">EXECUTIVE SUMMARY</p><h3>Focus: '+esc(t.title)+'</h3><p>Atlas sees '+u+' time-sensitive decisions and '+money(a.reduce((n,o)=>n+o.value,0))+' in surfaced value. Your priority is <b>'+esc(goalType.value||g.type)+'</b>.</p></div><div class="memo-actions"><strong>Do next</strong><ol><li>Approve or defer '+esc(t.title)+' to protect its deadline.</li><li>Advance approved actions with a calendar commitment.</li><li>Ignore low-confidence signals until they gain a second source.</li></ol></div>'}
function sources(){sourcesEl.innerHTML=[['Grant and RFP radar','Ready for a feed/API connection','Demo signals'],['CRM and inbox listener','Requires account authorization','Approval-gated'],['News and competitor watch','Ready for RSS/API connection','No external access yet']].map((s,i)=>'<article class="source-card"><span class="source-status '+(i?'pending':'ready')+'"></span><h3>'+s[0]+'</h3><p>'+s[1]+'</p><small>'+s[2]+'</small><button class="outline connect">Configure</button></article>').join('');document.querySelectorAll('.connect').forEach(b=>b.onclick=()=>alert('This local demo needs your provider and OAuth/API credentials before it can connect.'))}
const goalRevenue=$('#goalRevenue'),goalHours=$('#goalHours'),goalType=$('#goalType'),goalRisk=$('#goalRisk'),simulator=$('#simulator'),simulationResult=$('#simulationResult'),strategyMemo=$('#strategyMemo'),sourcesEl=$('#sources'),saveGoals=$('#saveGoals'),refreshMemo=$('#refreshMemo');
saveGoals.onclick=()=>{g.revenue=Number(goalRevenue.value)||250000;g.hours=Number(goalHours.value)||30;g.type=goalType.value;g.risk=goalRisk.value;localStorage.setItem('atlas-goals',JSON.stringify(g));rs();alert('Strategy preferences saved locally.')};[goalRevenue,goalHours,goalType,goalRisk].forEach(x=>x.onchange=()=>{memo();sim()});refreshMemo.onclick=memo;document.querySelector('[data-view="strategy"]').onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='strategy'));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view==='strategy'));$('#title').textContent='Strategy lab';rs();scrollTo(0,0)};rs();
});

const seed=[
{id:1,title:'Statewide AI workforce grant',org:'Colorado Office of Future Work',source:'GRANT RADAR',value:75000,deadline:'2026-09-08',fit:94,urgency:97,confidence:88,effort:45,status:'needs-review',summary:'A strong match for your workforce analytics expertise. The application window closes in seven days.',action:'Approve proposal outline',sources:['CO Future Work — Program notice','State procurement calendar'],tags:['Grant','High fit']},
{id:2,title:'Data partnership with Brightpeak',org:'Brightpeak Health',source:'WARM INTRO',value:120000,deadline:'2026-09-18',fit:89,urgency:75,confidence:82,effort:55,status:'needs-review',summary:'Their VP of Data asked for a discovery call after seeing the recent case study.',action:'Approve outreach email',sources:['Email from Jordan Lin','Brightpeak Q3 strategy update'],tags:['Partnership','Warm']},
{id:3,title:'Public-sector analytics RFP',org:'City of Aurora',source:'RFP MONITOR',value:210000,deadline:'2026-09-25',fit:82,urgency:61,confidence:77,effort:76,status:'watching',summary:'Large contract with a favorable capability match, but requires a partner for implementation.',action:'Identify delivery partner',sources:['Aurora procurement portal','RFP 26-184'],tags:['RFP','Strategic']},
{id:4,title:'Healthcare forecasting advisory',org:'Northstar Clinics',source:'CRM SIGNAL',value:38000,deadline:'2026-09-12',fit:91,urgency:84,confidence:73,effort:38,status:'approved',summary:'Existing relationship signals a compact, high-margin advisory engagement.',action:'Schedule discovery call',sources:['HubSpot activity','Northstar annual report'],tags:['Client expansion','Fast path']},
{id:5,title:'University research consortium',org:'Front Range University',source:'NEWS WATCH',value:50000,deadline:'2026-10-03',fit:73,urgency:38,confidence:67,effort:65,status:'watching',summary:'Early signal around a research consortium with potential long-term strategic value.',action:'Monitor announcement',sources:['University research bulletin'],tags:['Research','Long-term']}];
let data=JSON.parse(localStorage.getItem('atlas-opps')||'null')||seed,log=JSON.parse(localStorage.getItem('atlas-log')||'null')||[{text:'Imported 5 opportunity signals from connected monitors.',date:'Today, 8:10 AM',action:'SYSTEM'}],filter='all';
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),score=o=>Math.round(o.fit*.3+o.urgency*.22+o.confidence*.23+(100-o.effort)*.15+Math.min(o.value/1500,10)),days=o=>Math.max(0,Math.ceil((new Date(o.deadline)-new Date())/86400000)),save=()=>{localStorage.setItem('atlas-opps',JSON.stringify(data));localStorage.setItem('atlas-log',JSON.stringify(log))},esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(o){return `<article class="card opportunity" data-id="${o.id}"><div class="top"><span class="source">${o.source}</span><span class="score">${score(o)} SCORE</span></div><h3>${esc(o.title)}</h3><p class="muted">${esc(o.org)}</p><span class="tag">${o.tags[0]}</span><div class="bottom"><span>${money(o.value)}</span><span>${days(o)} DAYS LEFT</span></div></article>`}
function render(){let top=[...data].sort((a,b)=>score(b)-score(a)),pending=data.filter(x=>x.status==='needs-review');$('#topCards').innerHTML=top.slice(0,3).map(card).join('');$('#pipelineCount').textContent=data.length;$('#approvalCount').textContent=pending.length||'';$('#reviewCount').textContent=pending.length;$('#signalScore').textContent=Math.round(top.slice(0,3).reduce((a,x)=>a+score(x),0)/3);$('#stats').innerHTML=[['Pipeline value',money(data.reduce((a,x)=>a+x.value,0)),'+18% this week'],['Qualified signals',data.length,'2 new today'],['Decision latency','4.2 hrs','−31%'],['Actions protected','100%','approval-gated']].map(x=>`<div class="stat"><p>${x[0]}</p><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('');pipeline();approvals();memory();bind()}
function pipeline(){let r=data.filter(o=>filter==='all'||o.status===filter),q=$('#search').value.toLowerCase();r=r.filter(o=>(o.title+o.org).toLowerCase().includes(q));let s=$('#sort').value;r.sort((a,b)=>s==='deadline'?new Date(a.deadline)-new Date(b.deadline):s==='value'?b.value-a.value:score(b)-score(a));$('#pipelineList').innerHTML=r.map(o=>`<div class="row"><span class="score">${score(o)}</span><div><h3>${esc(o.title)}</h3><span class="muted">${esc(o.org)} · ${o.source}</span></div><div class="metric">${money(o.value)}<br><span class="muted">${days(o)} days left</span></div><span class="status ${o.status}">${o.status.replace('-',' ')}</span><div><button class="outline inspect" data-id="${o.id}">Inspect →</button></div></div>`).join('')||'<p class="muted">No signals match this view.</p>'}
function approvals(){let r=data.filter(o=>o.status==='needs-review');$('#approvalList').innerHTML=r.map(o=>`<article class="approval"><div><p class="eyebrow">${o.source} · SCORE ${score(o)}</p><h3>${esc(o.title)}</h3><p class="muted">${esc(o.summary)}</p><div class="action-row"><button class="primary approve" data-id="${o.id}">Approve action</button><button class="outline reject" data-id="${o.id}">Pass for now</button><button class="outline inspect" data-id="${o.id}">Inspect evidence</button></div></div><div class="recommend"><strong>ATLAS RECOMMENDS</strong><span>${esc(o.action)}</span><div class="bar"><i style="width:${score(o)}%"></i></div><p class="muted">${o.fit}% strategic fit · ${o.confidence}% evidence confidence</p></div></article>`).join('')||'<div class="approval"><div><h3>All clear.</h3><p class="muted">There are no actions awaiting your approval.</p></div></div>'}
function memory(){let n=log.filter(x=>x.action==='APPROVED').length;$('#memoryCards').innerHTML=[['Strategic-fit preference','Atlas gives proven capability matches more weight.',Math.min(92,70+n*5)],['Speed-to-value preference','Shorter paths from signal to action are prioritized.',78],['Evidence threshold','Recommendations require corroborated source evidence.',85]].map(x=>`<article class="memory"><h3>${x[0]}</h3><p class="muted">${x[1]}</p><div class="bar"><i style="width:${x[2]}%"></i></div></article>`).join('');$('#log').innerHTML=log.slice(0,8).map(x=>`<div class="log-item"><span>${esc(x.text)}</span><span><span class="log-action">${x.action}</span> · ${x.date}</span></div>`).join('')}
function detail(id){let o=data.find(x=>x.id==id);$('#detailContent').innerHTML=`<div class="detail-title"><p class="eyebrow">${o.source} · EXPLAINABLE RECOMMENDATION</p><h2>${esc(o.title)}</h2><p class="muted">${esc(o.org)} · deadline ${o.deadline}</p></div><div class="detail-grid"><div class="detail-metric"><label>OPPORTUNITY SCORE</label><strong>${score(o)}/100</strong></div><div class="detail-metric"><label>POTENTIAL VALUE</label><strong>${money(o.value)}</strong></div><div class="detail-metric"><label>RISK LEVEL</label><strong>${o.effort>65?'Moderate':'Low'}</strong></div></div><div class="reasons"><strong>Why Atlas ranked this highly</strong><ul><li>${o.fit}% capability and strategic fit</li><li>${o.confidence}% evidence confidence across ${o.sources.length} cited sources</li><li>${days(o)} days until deadline; urgency is factored into the score</li><li>Estimated delivery effort: ${o.effort}/100</li></ul></div><p class="eyebrow" style="margin-top:20px">CITED RESEARCH</p><p class="muted">${o.sources.map(esc).join(' · ')}</p><p class="eyebrow" style="margin-top:20px">APPROVAL-GATED DRAFT</p><div class="draft">Subject: Exploring ${esc(o.title)}\n\nHi [Name],\n\nI saw the opportunity to support ${esc(o.org)} and believe our experience is unusually well aligned. Would you be open to a short conversation this week to explore the objectives and a practical next step?\n\nBest,\nAlex</div>`;$('#detail').showModal()}
function decide(id,status){let o=data.find(x=>x.id==id);o.status=status;log.unshift({text:`${status==='approved'?'Approved':'Deferred'}: ${o.title}`,date:'Today, just now',action:status==='approved'?'APPROVED':'DEFERRED'});save();render()}
function bind(){document.querySelectorAll('.opportunity,.inspect').forEach(e=>e.onclick=()=>detail(e.dataset.id));document.querySelectorAll('.approve').forEach(e=>e.onclick=()=>decide(e.dataset.id,'approved'));document.querySelectorAll('.reject').forEach(e=>e.onclick=()=>decide(e.dataset.id,'watching'))}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#title').textContent=({briefing:'Good morning, Alex.',pipeline:'Opportunity pipeline',approvals:'Your decision queue',memory:'How Atlas learns'})[v];scrollTo(0,0)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#search').oninput=pipeline;$('#sort').onchange=pipeline;document.querySelectorAll('.chip').forEach(e=>e.onclick=()=>{filter=e.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===e));pipeline()});$('#add').onclick=()=>$('#intake').showModal();document.querySelectorAll('.close').forEach(e=>e.onclick=()=>e.closest('dialog').close());$('#form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),deadline=f.get('deadline'),o={id:Date.now(),title:f.get('title'),org:f.get('org'),value:+f.get('value'),deadline,summary:f.get('summary'),source:'MANUAL INTAKE',fit:82,urgency:Math.min(98,100-days({deadline})),confidence:65,effort:55,status:'needs-review',action:'Review and approve outreach',sources:['Manual intake — pending verification'],tags:['New signal']};data.unshift(o);log.unshift({text:`Added and scored: ${o.title}`,date:'Today, just now',action:'INTAKE'});save();e.target.reset();$('#intake').close();show('approvals');render()};$('#reset').onclick=()=>{localStorage.clear();location.reload()};$('#date').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();render();
